receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    timeout: 5s
    send_batch_size: 100

  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

  cumulativetodelta:

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    traces_index: "vehicletype-traces"
    logs_index: "vehicletype-logs"
    metrics_index: "vehicletype-metrics"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter, cumulativetodelta]
      exporters: [elasticsearch]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
  telemetry:
    logs:
      level: debug